name: dart_pandas
description: An analog of the pandas library in python
version: 0.2.2
repository: https://github.com/Anykeykin/dart_pandas

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  csv: ^6.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
